name: Health-heck

on:
  schedule:
    - cron:  '5 * * * *'

jobs:
  health_check_job:
    runs-on: ubuntu-20.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://pokemonsapplication351.herokuapp.com/
        follow-redirect: false
        max-attempts: 2 
        retry-delay: 5s
